# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout EthernetLarge library
      uses: actions/checkout@v3
      with:
          repository: OPEnSLab-OSU/EthernetLarge
          ref: master
          path: CustomLibrary_EthernetLarge # must contain string "Custom"

    - name: Compile sketch
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp32:esp32:m5stack-atoms3:CDCOnBoot=cdc
        arduino-platform: esp32:esp32@2.0.15
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: M5AtomS3@1.0.0,M5Unified@0.2.0,OneWire@2.3.8,DallasTemperature@3.9.0,M5-ADS1115@1.0.0,M5Unit-ENV@1.0.1,NewPing@1.9.7,Adafruit_VL53L0X@1.2.4,Adafruit SGP30 Sensor@2.0.3,Adafruit BME680 Library@2.0.5,Adafruit VEML7700 Library@2.1.6,SparkFun AS7331 Arduino Library@2.1.1,SparkFun AS3935 Lightning Detector Arduino Library@1.4.9,M5-Ethernet@4.0.0,M5GFX@0.2.0,SSLClient@1.6.11,UrlEncode@1.0.1
        sketch-names: "*.ino"
        sketch-names-find-start: bbn_*/*
        extra-arduino-cli-args: "--warnings default"
        set-build-path: true
